name = "apollo"
version = "0.1.1"
description = "a simple type safe validator"

licences = ["MIT"]
repository = { type = "github", user = "enderchief", repo = "apollo" }
gleam = ">= 0.32.0"

[javascript]
typescript_declarations = true

[dependencies]
gleam_stdlib = "~> 0.34"

[dev-dependencies]
gleeunit = "~> 1.0"
